services:
  db:
    image: postgres:14.4-alpine
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: postgres
    ports:
      - "127.0.0.1:5432:5432"
volumes:
  postgres_data:
