---
- name: Install kubectl binary manually
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x kubectl
    sudo install kubectl /usr/local/bin/kubectl
  args:
    creates: /usr/local/bin/kubectl
- name: Verify kubectl installation
  command: kubectl version --client
  register: kubectl_version
- debug:
    msg: "kubectl version installed: {{ kubectl_version.stdout }}"

- name: Bash completion for Kubectl
  shell: | 
    kubectl completion bash > ~/.kube/completion.bash.inc
    printf "
    # kubectl shell completion
    source '$HOME/.kube/completion.bash.inc'
    " >> $HOME/.profile