---
- name: Install Terraform on target systems
  hosts: ansible
  become: yes
  tasks:

    - name: Ensure dependencies are installed
      apt:
        name: 
          - curl
          - unzip
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Download the Terraform binary
      shell: |
        T_VERSION=$(curl -s https://releases.hashicorp.com/terraform/ | grep -oP 'terraform/\K[0-9]+\.[0-9]+\.[0-9]+' | head -1)
        curl -Lo /tmp/terraform.zip "https://releases.hashicorp.com/terraform/${T_VERSION}/terraform_${T_VERSION}_linux_amd64.zip"
      args:
        creates: /tmp/terraform.zip

    - name: Unzip Terraform binary
      ansible.builtin.unarchive:
        src: /tmp/terraform.zip
        dest: /usr/local/bin/
        remote_src: yes
        creates: /usr/local/bin/terraform

    - name: Set executable permissions for Terraform
      file:
        path: /usr/local/bin/terraform
        mode: '0755'

    - name: Verify Terraform installation
      command: terraform version
      register: terraform_version
      ignore_errors: yes

    - debug:
        msg: "Terraform version installed: {{ terraform_version.stdout }}"
