---
- name: Download Github Runner tarball manually
  shell: |
    mkdir actions-runner
    curl -o /home/vagrant/actions-runner-linux-x64-2.321.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.321.0/actions-runner-linux-x64-2.321.0.tar.gz
  args:
    creates: /home/vagrant/actions-runner-linux-x64-2.321.0.tar.gz

- name: Validate the hash
  command: echo "ba46ba7ce3a4d7236b16fbe44419fb453bc08f866b24f04d549ec89f1722a29e  actions-runner-linux-x64-2.321.0.tar.gz" | shasum -a 256 -c

- name: Extract Github Runner tarxball
  command: tar xzf /home/vagrant/actions-runner-linux-x64-2.321.0.tar.gz -C /home/vagrant/actions-runner