---
- name: Ensure curl is installed
  package:
    name: curl
    state: present
- name: Copy file to remote hosts
  ansible.builtin.copy:
    src: hosts
    dest: /home/vagrant/hosts
- name: Add hosts to /etc/hosts
  shell: |
    cat /home/vagrant/hosts >> /etc/hosts
- name: Disable UFW
  shell: |
    ufw disable
- name: Install K3s on master node
  shell: |
    curl -sfL https://get.k3s.io | sh -
  args:
    creates: /etc/systemd/system/k3s.service
- name: Get the K3s join token on the master
  shell: |
    cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token
