name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend-src

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          backend:
            - 'backend-src/**'  

    - name: Get semantic version
      id: version
      uses: paulhatch/semantic-version@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:${{ steps.version.outputs.version }} .

    - name: Push Docker image to registry
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ steps.version.outputs.version }}

    - name: Set up Kubernetes kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_FILE }}" > kubeconfig
        chmod 600 kubeconfig
      env:
        KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_FILE }}

    - name: Deploy to Kubernetes
      uses: azure/setup-kubectl@v3

    - name: Apply Kubernetes manifests
      run: |
        sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/my-app:${{ steps.version.outputs.version }}|" k8s-manifest.yaml
        kubectl apply -f k8s-manifest.yaml --kubeconfig=kubeconfig
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG_FILE }}
